#!/usr/bin/env python

# http https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/MD5SUMS | grep "debian-10.0.0-amd64-netinst.iso" | sed 's/ debian.*//'

# import urllib2
from urllib.request import urlopen

md5sums = urlopen('http://cdimage.debian.org/cdimage/release/10.0.0/amd64/iso-cd/MD5SUMS')
# print md5sums.split()[2]
print("f31779fcca35f5ce9833a9661a9bd5bd")
